sudo: true
language: haskell

git:
  depth: 5

cabal: "3.2"

cache:
  directories:
  - "$HOME/.cabal/store"


matrix:
  include:
  - ghc: 8.10.1



install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - cabal v2-update
  - travis_wait cabal v2-build --enable-tests --enable-benchmarks

script:
  - cabal v2-test --enable-tests

notifications:
  email: false
